<a href="https://colab.research.google.com/github/bilalkhan18/Deep-Learning-/blob/main/Chatbot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# Define the questions and answers
questions = ["hi","what is your name?","bye"]
answers = ["Hello","My name is Chatbot.","Good bye"]

In [3]:
# Define a vocabulary and mapping from words to indices
l=(" ".join(questions)).split()
vocab={j:i for i,j in enumerate(l)}
print(vocab)

{'hi': 0, 'what': 1, 'is': 2, 'your': 3, 'name?': 4, 'bye': 5}


In [4]:
# Convert the questions and answers to numerical form
X = np.zeros((len(questions), len(vocab)), dtype=np.float32)
Y = np.zeros((len(answers), len(answers)), dtype=np.float32)
for i, question in enumerate(questions):
    for word in question.lower().split():
        if word in vocab:
            X[i, vocab[word]] = 1.0
    Y[i, i] = 1.0
print(X)
print(Y)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
# Define the neural network model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(len(vocab),)),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(len(answers), activation='softmax')
])
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [6]:
# Train the model on the questions and answers
model.fit(X, Y, epochs=10)

Epoch 1/10
1/1 [==============================] - 2s 2s/step - loss: 1.2089 - accuracy: 0.0000e+00
Epoch 2/10
1/1 [==============================] - 0s 15ms/step - loss: 1.1769 - accuracy: 0.0000e+00
Epoch 3/10
1/1 [==============================] - 0s 13ms/step - loss: 1.1465 - accuracy: 0.0000e+00
Epoch 4/10
1/1 [==============================] - 0s 16ms/step - loss: 1.1185 - accuracy: 0.0000e+00
Epoch 5/10
1/1 [==============================] - 0s 20ms/step - loss: 1.0933 - accuracy: 0.3333
Epoch 6/10
1/1 [==============================] - 0s 15ms/step - loss: 1.0688 - accuracy: 0.3333
Epoch 7/10
1/1 [==============================] - 0s 18ms/step - loss: 1.0449 - accuracy: 0.3333
Epoch 8/10
1/1 [==============================] - 0s 12ms/step - loss: 1.0218 - accuracy: 0.3333
Epoch 9/10
1/1 [==============================] - 0s 14ms/step - loss: 0.9992 - accuracy: 0.3333
Epoch 10/10
1/1 [==============================] - 0s 14ms/step - loss: 0.9769 - accuracy: 1.0000


In [7]:
# Define a function to generate a response from the model
def generate_response(input_text):
    x = np.zeros((1, len(vocab)), dtype=np.float32)
    for word in input_text.lower().split():
        if word in vocab:
            x[0, vocab[word]] = 1.0
    y = model.predict(x)[0]
    index = np.argmax(y)
    print(index)
    return answers[index]

In [8]:
# Ask for user input and generate a response
while True:
    user_input = input("You: ")
    if user_input.lower() == "exit":
        break
    response = generate_response(user_input)
    print("Chatbot:", response)

You: Hello
1/1 [==============================] - 0s 87ms/step
0
Chatbot: Hello
You: What is your name
1/1 [==============================] - 0s 20ms/step
1
Chatbot: My name is Chatbot.
You: Bye
1/1 [==============================] - 0s 23ms/step
2
Chatbot: Good bye
You: sdasdvdw
1/1 [==============================] - 0s 22ms/step
0
Chatbot: Hello
You: rgergqrhthrwjyuj6teyyrhrwht
1/1 [==============================] - 0s 23ms/step
0
Chatbot: Hello
You: exit
